### ISSUE TITLE
Cannot find tpromise.h

### ISSUE THREAD

**Issue by nestorac** [theCheeseboard/theFrisbee#1]
Hello, I want to use your library as an example for building a Qt5 app GUI for safely erasing disks.

I see that you use a library called tpromise.h, but I cannot find it, where is it? Thank you!

**Comment by vicr123** [comment]
tPromise is part of the-libs: https://github.com/vicr123/the-libs

I should warn you that theFrisbee is beta software and stuff may not work properly :)

**Comment by nestorac** [comment]
Thank you! I'm just trying to use existing code in a new app to erase disks. Let's say, I'm doing seamstress work (I don't exactly know how to say "trabajo de costurera"), joining pieces of code, to start fast. If I find any mistake in your code, of course, I'll notify you, but I'm just interested in some pieces of code.

**Comment by vicr123** [comment]
It may be helpful to reference the udisks documentation if you're interested in anything else, for example, creating partitions: http://storaged.org/doc/udisks2-api/latest/

Good luck with your project :)
