### ISSUE TITLE
application/jobs/restoreopticaljob.cpp: line 175, error: ‘SkipEmptyParts’ is not a member of ‘Qt’

### ISSUE THREAD

**Issue by nestorac** [theCheeseboard/theFrisbee#3]
I get this error in application/jobs/restoreopticaljob.cpp:175 and optical/opticalerrortracker.cpp:78.

https://doc.qt.io/qt-5/qstring-obsolete.html

**Comment by nestorac** [comment]
I have changed `Qt::SkipEmptyParts` with `QString::SkipEmptyParts` and it works.

**Comment by vicr123** [comment]
You'll need to build this witl a later version of Qt. 5.15 is recommend :)
